### ISSUE TITLE
Rebrand this project?

### ISSUE THREAD

**Issue by SiboVG** [Aspirata/Mcblend#15]
Hey, this looks like a promising addon, but it is quite confusing that there exists another Blender addon called Mcblend: https://github.com/Nusiq/mcblend.

I think it may be wise to rebrand this project, to avoid confusion with other users.

**Comment by Aspirata** [comment]
Yeah, i was thinking about rebranding, but i don't have any idea

**Comment by SiboVG** [comment]
Could you share what your big picture vision is for this project? Is it just for polishing world imports (in that case you could rebrand to MCpolish), or do you also want to include advanced assets, effects, etc.?

**Comment by Aspirata** [comment]
It's similar to MCprep, but different

**Comment by SiboVG** [comment]
Some suggestions:
- MCpolish (also hinting to MCprep)
- BlendCraft (though this is already used a lot in other Blender Minecraft tools)
- MinAnim (Minecraft Animator tool)

**Comment by lynrayy** [comment]
+++
It was hardly possible to find this project. It's called the same as the other one (useless)

**Comment by Aspirata** [comment]
Well, I still don't have a good idea for the name of this addon

**Comment by lynrayy** [comment]
Blend-Imator

**Comment by Aspirata** [comment]
> Blend-Imator

Sounds more like a thing for mine-imator

**Comment by SiboVG** [comment]
> Some suggestions:
> 
> * MCpolish (also hinting to MCprep)
> * BlendCraft (though this is already used a lot in other Blender Minecraft tools)
> * MinAnim (Minecraft Animator tool)

In addition to these previous suggestions, I'd also like to add **AniMine** (Animate Minecraft)

**Comment by Aspirata** [comment]
> AniMine

This addon doesn't give you any animation tools, and I don't think I'll be adding any

**Comment by Aspirata** [comment]
Hmmm, what about Aurora ? That name isn't so convinient as Mcblend, but it sounds cool

**Comment by SiboVG** [comment]
> Hmmm, what about Aurora ? That name isn't so convinient as Mcblend, but it sounds cool

Not a big fan. IMO the name should hint to MineCraft.

**Comment by Aspirata** [comment]
As you can see, I renamed Mcblend to MiBlend
