### ISSUE TITLE
Rig on v3.6

### ISSUE THREAD

**Issue by lynrayy** [Aspirata/Mcblend#37]
Please backport rig to the blender 3.6. It crashes when i'm opening simple edit rig

**Comment by Aspirata** [comment]
![image](https://github.com/user-attachments/assets/d58e21ff-f16c-4807-8068-fcb046501b80)

I tested the latest commit on blender 3.6.13 and all the rigs work fine

**Comment by lynrayy** [comment]
It is my issue, 3.5 broken but 3.6 works fine
